apiVersion: v1
items:
-   apiVersion: v1
    data:
        token: ENC[AES256_GCM,data:A6gfPV4RCG3zQFYpmHvPO+Sys0/qfIQj1Of5Ogkuza4Ux0J+lVDifj73nTDoVmRsdrIkuCb5Cs+8MO9zsUb4WJ8MCW5jjd2EotzHd1SHBjfpV1YfBZ6/i8aPVhaPPLz0O+E3d/vvGW8euPAJKKkvLMEMbsq2i+dsiDGxJBD6IBTP6y8+u9bo4YeHCUYt0aohapkLSVR6lEmQ9izA/uLGfB4kvHviu56/viSEGMmG1F25jQ/WSQsNkpCx/9yPRgmWdbkxbgr9o4XIacyp2vfPCMDfvRlUG/DuASbRWNJlQSnh5SgCH2wz0lCAtCc2Ebs9WYioj9Nz91Egm4oqf3sf6bJL9DkU7QB/HfKIOKXVAZcBymwqZ0oejxXBG3i7Hs9OSMWRxKI9irQglNAVfUMFBHZajJMYuejJVFNsqU6NnKGbS2LmNBZP7cZaa1ZyBdOwaiA8tg2rbBbcgahZ0XFwa7YoxE3HsJl3gOKdp0EDTTSl8aP/jLxTtBXxw9GWFUr/XWRbQE8ykPBBP1nTwnoI/dEKu9k0pwy19nr6qnDt9xgEnDTdcaYmF0CsHyrIBmkWpCxeAlljSj4Yl5/bcb2YkSlHsgyxsaQnBD5nyt63MdQXQKxDjINuT/eDvz0UzuNdym2uzX5BmREjZD5RkmaJvYXoJwu9uFqMLL9gkd5jbGWhE+AWPbt40P6ISm6qdXSai0hAkTmbFNA9CQFqAd68lSxYFufPJhySyiF2Q7ThLVgm4jkoMgx8To/avQdEfjmuDcbzsMI0gy2uA8ELb5Yse4OjbjzrDoWNhSWTqXrp3+qUDGDXHhjTVfzFRo+JotWGg+l8y8Eqi0/qii1Vsjm0aVoAC76pYPqjA/1ctnErt5D6jyDkH+zrgVP1OdZKOIVjTzNqMJm6VESY/6X6ol77PxJynvXBvT8pOdZPtQ6Rze/xCVPgxHn3taQpeVNgBu7l16pQrAApsk0vwOyZ+2AHUa3hCKOL0XWN89UH+swve79flHg8taLwPZ1yxsMYyhlG0Wdc8hcxGtqFMOs7dokYw1g9qXp4BWyeTVpr7mwJh4+4yYdWJ0jK4Q91r+Cj9nRnI1VpS+GiTKD8U8x/xlu5Y/OtfU5hb2wj0LYL884zUOQzo74Ub/IFCffdxoZM6KWlSYfAWYe4Uk1+wi1wK4yUsAKloLHXVZbCqgDeMfUVapf7qki58Fe2UZZ2VhAYv7OCflJDvl6OtejcUFOq7X1T0qfTbOj3H3S1ybQoD+oHJsLtr3cB4uRSrAVwvGUPfucLQdIvj7pDiqo1+iYYn2mdjOfgP/XdzBVQx0DHFsfl3ImtrnZnZAqoM11XvI8awyuiRxirvrcSbxLCWJ0+Z/j3+NgCBD4+azWURe3xhGv0mW7HOLuRV80D/D7AeOyFt4oOInyizaTnjSz483bWExPXvGLyGykBm6cklSWQcUJ/GZ1QSnVvCNLEjS54AI/zQaGuBW1AI61LTRSK1E4rPB8C3UEFy7UG2xUs+Xw+MMarCiYKxJaUOKCWKVaCg8T/v8KdvlJxxqGKtqmxeA26ajOWaz+Z4KygSjHFC3vXgslk9FKhDTZO+yyxLXqHL1rPJdB1G9zP2+0TGMGRyraGpI03EtrtTqF56Y3HIpmseIhtZKU=,iv:MYBseqaVidbq2a+m8Vtj/ThDiJt7CcdQ/SSlZvchcdE=,tag:C/yQ1ESjQ8dzEEsWlo/uqg==,type:str]
    kind: Secret
    metadata:
        name: slo-reporter
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-03-10T18:52:45Z'
    mac: ENC[AES256_GCM,data:ZQR0Kj5XoVsnl1I3aYldscxGjMme3OHno5+46rx1yoXOe/R01T7ISh92mfMQH7ptRqKwgviR9vo78G53OJ9XnzHhKyda6+lkEWu+ned0jPU4PQMleLssL/y74N2OfjrIFINoYfCBnjL7fEvakCtWXX7SNajvGdJQ4z/3RFdTtZ0=,iv:9X2yiy1JJ8/rA/ETLKrOPWmC1i9Gp6n0EQaBXB9PDjc=,tag:yEpTY/NvisPJuzO2ZehXZQ==,type:str]
    pgp:
    -   created_at: '2021-03-10T18:52:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ//VDZma5lUWJAN6/muOaUptAAwj0XzCPuSX9xqkfZQMkeL
            UbZVe3eXw6CoGKy1/JOpPJKE0Qt3d0zufhXcAeiHycnKLClMbGQEX/OXFNgI0KGw
            8AaM2Y/YbViioNjCmR4Ptzl3SSFWpX2ZTpw6fwpN0gr9NtUT/fuLMowXR10PQ9q8
            bfRRcXnj2vDQVdbTTUhDKBBHCu0DvO/cXFoxFJUx+Z5Vda2gwcYFo0OKGw0gH89B
            kpaC1O8QUfzyRI3VoLvD4G/8VRmLFF7Jzc5sGedXS3hlOiMyKPxFb6LUbv711Lcl
            lBtzSu39il1nBUP7sfIUXX6dxZ31+rZA/5zbVyp4nsdGe8ymX9/hrpiXnvwqW2qe
            oKQyUyaaSGRyiz1n95IvsLZLHyw6shb4ME5qnBIhI8BF3yOMgWmNDRPdMu2MkVG1
            PKj3jUXtL373e5ziHLokqzYzzvYdSy2uoxvgQ96WgtBKtZXwoLFVRLW3cpUeT25H
            jy01OmS4xkvH9IxrhV+Zy39h6OCPFmiYC88vp1WhNrbn3oehgyBvyn659iO0OI4z
            LKTF2oEDbZ4D7d224LwvkjYoY4dmJdC9JE7I7XqhoHD8hfw9PO1imdqJ8oEfYFpA
            Aq964ME6/Bye7zPNDcDnyzFLxRR9g6lM7PxAxak7fqAoBY04yazXCcuR0+DoNaXS
            XAEYoR5KVPkhi0OisLMOqSnw39oe17Xuwa7FZtPMyUn/qdtX4Uo3Abka1HuYcMEu
            5qs9NckeMfZ0GAC5+BWoJlFepd5f7nZLbjgz+W2US5QS4f6o1clPV3aVqCrw
            =6dKC
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-03-10T18:52:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/WiYk7jciJ2YQfgy194vT7J27T6tu3Ebag28njQNcoYJH
            wRZQH50cN1U7isBvAEH844gYVg3nezpiGdyrSz06o1KqAvQkYoY/YwbED5fcEsMT
            6sY8FLFwRe8x9h1nPlNiB7vG3R6e4B+jtDLZ5WYieQQd4lVX9WgwbJ+3UQfVHxvI
            trTURyNj7HmKkDkLqTpdR49450SVrKzCI9H+qhry/okoNq/ffap6KYjypDVieN5V
            JPZOLHVLz7hAGX88eutjL5xAxXmnUGmAIvITAZGezHiuPBkDMM95gRC0L2Ge3vX7
            T8xVbOnhf2WBezqHUEMTpCxMdAr02hmJAy6u2Ex+w9JcAX4M6l3a5Cp0b1g2mGFB
            y/ULnZ3jl03kNzba6PlLlhep+mLj1o1TFMXPuVlE/mu9gCRslhPuzDYTJNE80M2V
            qKmc0R5iqUyYorpHVPS3KsV5g+0own0uoRTtRlI=
            =g7xl
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-03-10T18:52:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+MJ396wPr73e6WsVcme6QZh/j1KVXO6PeBQ+KR9M+Gsc9
            wBJUUjunDqdyrvl4EnJl+MD58MzjQJ58ubHZHtYMLWO3E72yOrsE6PHG1+MlmTrh
            RZnUD6Vo3913LxKPCnHZ5bPVwKMDP634XjFOrS0Xb9AukkXROSKrrPatie+duKfo
            0x3/cJqtM5l6naR38V+NDNkqhiHvzhu0bLcbxwzJc+KZVNRQUD8KEd6B7oKAYP3H
            kjyyCacI2ncQVYA2bxlmOQmsGQB+XgYEbpiT68k4d0W4DBZysqJXxrJIlxqC4X0W
            isFJfa35q8LqVSzpB2Cok0k2Yi9KqBIiWS+KKv/JRtJcAfEiBHvv+qMijArnxvqX
            O7XESU4t+YXEnpzSXl+UCHdrLKjlR2mZ812kdgLUDC9AySpE9uBi6aIlJLZcIncE
            D3BFZeTB9cctL6mofxzzGQgpKVRknQHKtpUpwY0=
            =Dsz/
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-03-10T18:52:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//dwM1u91dd/UP4BFePAGoFRAtC5hgruLwf4/XoiE4xVgT
            gHSjYdk6E50Pus/gtWxH0GfqUElSov6oOD5/wEMCfxa4hnH0KdC4zFPEeFRns2Qe
            l7RTlqemE1h93spDXDa/xZJIjH8GUYJiosNuuOdGpznW1xF6SYb+EX5CtB2uYj4a
            /bmHFig/red+Rfuwl0GpaOJ9D9oFpS+5hWiEO3V6tJJzleVc9LIVpeHFs6/Bbokh
            bvyEXUNTJf8+0o5j3aP/j+BDfyZHBRghGoKimDM4AJT5wB9Us8L5NCbYWfiuYU7m
            XISKm5SEFChmKhBzxugi8OTYez6S4Mfs7Zagq/1Dbd0qIuBMsBPFgx1r39HP4Idj
            EwPGPFjUU2Sq+dnuYzYaHS1kqWwRgT/6Bcmmk0i0YWKaCA/x22jVC0Nve4Jds1OO
            6iHpc80lh6hIflWkS/gr1Vwj5Dwj/DserzVd7z/MS+SSptz7iPGgyQD6OG6suHN4
            tF5vfLON0OhomEgZQvlPUIMAmBJErLOcRLB4M0k/mKVtUEfPrmj6xON1WlJOVhMd
            V08amRW4o3rXO0bVpDYoD7xfQTpMKyPrqy2oUN11Ru1UDKYOoNSugaPIl16FMEdn
            qbFfr92jTdJQfyWZnM5IZOlFGewwMDwhYCqAPKMVx8saDLJWnJUpM+aFulaQsYjS
            XAEgbs9kvGGSikBtgZem8MOkRtgABPy2r2GazVwCZe0QrKEP2YPg2p4WBpb8stwL
            KvKHxhhVmsh2VbNSFMlJ58oCHBpbMu2+aif9yDNWOeBAoQmmQpODobmoNw8A
            =EqXa
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
