apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmap.yaml
  - cronjob.yaml
  - imagestreamtag.yaml
generators:
  - ./secret-generator.yaml
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-success-
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-fail-
