---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-watcher
data:
  build-analysis-no-build-log: "0"
  # We do not need to extract packages out of container images. We have
  # inspection specification where all the relevant information can be found.
  # No need to add these data to the database.
  build-analysis-no-base-image: "1"
  build-analysis-no-output-image: "1"
  kubernetes-verify-tls: "0"
  log-build-watcher: "INFO"
  logging-no-json: "0"
